feat: - criação da função do desafio 03 que calcula o fatorial de um …
erikabusiness/algoritmos_flutter pull request #15
Opened 2024-03-15 20:25 UTC by MendesEmerson

## Objetivo da tarefa
Crie uma função que inicialize um número inteiro. Como resultado, mostre na tela o fatorial desse número.
## O que foi feito
- Criação da função do desafio 03 que calcula o fatorial de um numero inteiro
- Adicionando a chamada dessa função dentro do switch
- Criando um novo item no dropdown menu
## Links úteis e dependências adicionadas

2024-03-15 22:41 UTC, lolaleid submitted a review, later dismissed
Obrigada pelo desenvolvimento do padrão de apresentação do aplicativo. Emerson, não seria interessante remover o break do switch?
Acredito que quando os desafios forem mesclados os demais desafios não são executados depois.

2024-03-16 14:25 UTC, vsjhonny approved these changes

2024-03-16 21:43 UTC, lolaleid requested changes
Por gentileza, remover o break depois da chamada na função.

2024-03-17 19:05 UTC, jcr04 approved these changes

2024-03-17 20:33 UTC, lolaleid approved these changes
Parabéns! Aprovado.

2024-03-18 15:12 UTC, MendesEmerson commented
Sobre a questão de remover os Break's da chamada dentro do switch, não será possível. Se remover todos os breaks ele vai chamar a função e logo depois vai bater no default do switch e isso vai nos trazer um comportamento inesperado.

2024-03-18 17:15 UTC, merged