feat: - criação da função do desafio 18  que inicializa uma palavra e mostra o resultado de quantas vezes foram repetidas.
erikabusiness/algoritmos_flutter pull request #23
Opened 2024-03-16 17:31 UTC by jcr04

## objetivo da terefa
Crie uma função que inicialize uma palavra e inicialize uma frase. Como resultado, mostre na tela quantas vezes aquela palavra aparece na frase, independente de letras maiúsculas e minúsculas.

## o que foi feito
- criação do desafio 18 que inicializa uma palavra e com uma frase e mostra na tela quanta vezes aquela palavra aparece na frase.
- foi adicionado a função e chamado ela dentro do switch.
- criação do item em um dropdown
## Links úteis e dependências adicionadas

2024-03-16 21:38 UTC, lolaleid requested changes
Olá João, você conseguiria reescrever as linhas 95 e 96 que foram removidas e retirar o break na linha 86 após a execução do seu desafio no switch? Pode deixar somente a chamada da sua função mesmo.
Quando os exercícios forem mesclados e o seu desafio for executado, os demais não poderão ser executados a seguir dessa forma.

Grata.

2024-03-17 19:24 UTC, jaquedreyer requested changes
Parabéns pela resolução! 
Apenas tem uma questão referente a como mostrar o resultado na tela.  Foi definido pelo time mostrar em duas variáveis ( _textoResultado = " " e  resultadoFinal = "") e o seu está todo em resultadoFinal, se puder alterar na linha 86 e 88 aí fica certinho!

2024-03-17 20:44 UTC, lolaleid approved these changes
Parabéns! Aprovado.

2024-03-18 14:57 UTC, vsjhonny approved these changes

2024-03-18 15:00 UTC, jaquedreyer approved these changes

2024-03-18 15:00 UTC, merged